"""Security hardening: RLS gaps, FORCE RLS, updated_at trigger, email unique fix

Revision ID: a1b2c3d4e5f6
Revises: 5e72375b1f12
Create Date: 2026-02-11 12:00:00.000000

Addresses the following audit findings:
- SEV-9:  Enable RLS + FORCE on user_sessions (was missing entirely)
- SEV-9:  Add FORCE ROW LEVEL SECURITY on all RLS-enabled tables
          (Alembic migrations only had ENABLE, not FORCE)
- SEV-8:  Enable RLS on mfa_configs via user_id → users join
- SEV-8:  Drop global unique constraint on users.email if it exists
          (multi-tenant uses composite ix_users_tenant_email instead)
- SEV-7:  Add notifications.tenant_id FK to tenants.id
- SEV-7:  Create set_updated_at() trigger function and apply to all
          tables with updated_at column (previously only Python-level onupdate)
"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1b2c3d4e5f6"
down_revision: str | None = "5e72375b1f12"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply security hardening changes."""

    # =========================================================================
    # 1. FORCE ROW LEVEL SECURITY on all RLS-enabled tables
    #    ENABLE was already done in migrations 001/004/006, but FORCE was only
    #    in the manual SQL script. Without FORCE, the table owner can bypass RLS.
    # =========================================================================
    _force_rls_tables = [
        "users",
        "roles",
        "api_keys",
        "notifications",
        "audit_logs",
        "oauth_connections",
        "sso_configurations",
    ]
    for table in _force_rls_tables:
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")

    # =========================================================================
    # 2. Enable RLS + FORCE + policy on user_sessions
    #    Migration 012 created the table but never enabled RLS.
    # =========================================================================
    op.execute("ALTER TABLE user_sessions ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE user_sessions FORCE ROW LEVEL SECURITY")
    op.execute("""
        CREATE POLICY user_sessions_tenant_isolation ON user_sessions
        FOR ALL
        USING (
            tenant_id::text = COALESCE(current_setting('app.current_tenant_id', true), '')
        )
        WITH CHECK (
            tenant_id::text = COALESCE(current_setting('app.current_tenant_id', true), '')
        )
    """)

    # =========================================================================
    # 3. Enable RLS + FORCE + policy on mfa_configs
    #    mfa_configs has no tenant_id column, so we filter through the users
    #    table FK relationship (user_id → users.id → users.tenant_id).
    # =========================================================================
    op.execute("ALTER TABLE mfa_configs ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE mfa_configs FORCE ROW LEVEL SECURITY")
    op.execute("""
        CREATE POLICY mfa_configs_user_isolation ON mfa_configs
        FOR ALL
        USING (
            user_id IN (
                SELECT id FROM users
                WHERE tenant_id::text = COALESCE(
                    current_setting('app.current_tenant_id', true), ''
                )
            )
        )
        WITH CHECK (
            user_id IN (
                SELECT id FROM users
                WHERE tenant_id::text = COALESCE(
                    current_setting('app.current_tenant_id', true), ''
                )
            )
        )
    """)

    # =========================================================================
    # 4. Drop global unique constraint on users.email (if it exists)
    #    Multi-tenant uniqueness is enforced by ix_users_tenant_email (tenant_id, email).
    #    The global unique was added by SQLAlchemy create_all() in dev if the model
    #    had unique=True (now removed from the model).
    # =========================================================================
    # Try to drop both possible constraint names that SQLAlchemy might have generated
    op.execute("""
        DO $$
        BEGIN
            -- Drop constraint generated by column-level unique=True
            IF EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conname = 'uq_users_email' AND conrelid = 'users'::regclass
            ) THEN
                ALTER TABLE users DROP CONSTRAINT uq_users_email;
            END IF;

            -- Drop possible alternative name
            IF EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conname = 'users_email_key' AND conrelid = 'users'::regclass
            ) THEN
                ALTER TABLE users DROP CONSTRAINT users_email_key;
            END IF;
        END $$;
    """)

    # =========================================================================
    # 5. Add FK on notifications.tenant_id → tenants.id (if missing)
    #    notifications.tenant_id existed but had no FK constraint.
    # =========================================================================
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conname = 'fk_notifications_tenant_id'
                AND conrelid = 'notifications'::regclass
            ) THEN
                ALTER TABLE notifications
                ADD CONSTRAINT fk_notifications_tenant_id
                FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
            END IF;
        END $$;
    """)

    # =========================================================================
    # 6. Create updated_at trigger function and apply to tables
    #    Previously only Python-level onupdate was used, which doesn't fire
    #    for direct SQL updates or updates from other clients.
    # =========================================================================
    op.execute("""
        CREATE OR REPLACE FUNCTION set_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = CURRENT_TIMESTAMP;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)

    _tables_with_updated_at = [
        "tenants",
        "users",
        "roles",
        "api_keys",
        "oauth_connections",
        "sso_configurations",
    ]
    for table in _tables_with_updated_at:
        trigger_name = f"trg_{table}_updated_at"
        op.execute(f"""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_trigger WHERE tgname = '{trigger_name}'
                ) THEN
                    CREATE TRIGGER {trigger_name}
                    BEFORE UPDATE ON {table}
                    FOR EACH ROW
                    EXECUTE FUNCTION set_updated_at();
                END IF;
            END $$;
        """)


def downgrade() -> None:
    """Revert security hardening changes."""

    # Drop updated_at triggers
    _tables_with_updated_at = [
        "tenants",
        "users",
        "roles",
        "api_keys",
        "oauth_connections",
        "sso_configurations",
    ]
    for table in _tables_with_updated_at:
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_updated_at ON {table}")

    op.execute("DROP FUNCTION IF EXISTS set_updated_at()")

    # Drop notifications FK
    op.execute("""
        ALTER TABLE notifications
        DROP CONSTRAINT IF EXISTS fk_notifications_tenant_id
    """)

    # Revert mfa_configs RLS
    op.execute("DROP POLICY IF EXISTS mfa_configs_user_isolation ON mfa_configs")
    op.execute("ALTER TABLE mfa_configs NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE mfa_configs DISABLE ROW LEVEL SECURITY")

    # Revert user_sessions RLS
    op.execute(
        "DROP POLICY IF EXISTS user_sessions_tenant_isolation ON user_sessions"
    )
    op.execute("ALTER TABLE user_sessions NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE user_sessions DISABLE ROW LEVEL SECURITY")

    # Revert FORCE RLS (keep ENABLE, just remove FORCE)
    _force_rls_tables = [
        "users",
        "roles",
        "api_keys",
        "notifications",
        "audit_logs",
        "oauth_connections",
        "sso_configurations",
    ]
    for table in _force_rls_tables:
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
